# Generated by Django 4.1.5 on 2023-01-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=1)),
                ("email", models.EmailField(max_length=30)),
                ("name", models.EmailField(max_length=255)),
                ("date", models.DateField()),
                ("cost", models.FloatField()),
                ("marks", models.IntegerField()),
                ("validity", models.IntegerField()),
                ("center_address", models.TextField(max_length=500)),
                ("result", models.BooleanField()),
            ],
        ),
    ]
