# Generated by Django 4.1.5 on 2023-01-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationdetails",
            name="feedback",
            field=models.TextField(default="Good", max_length=500),
        ),
        migrations.AddField(
            model_name="certificationdetails",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="certificationdetails",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
