# Generated by Django 4.1.5 on 2023-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0003_certificationdetails_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=30)),
                ("salary", models.FloatField()),
            ],
        ),
    ]
